[tool.poetry]
authors = []
description = "Code for final projects"
name = "src"
version = "0.0.0"

[tool.poetry.dependencies]
python = ">=3.9"
pandas = "1.4.1"
snakemake = "6.15.5"
owlready2 = "0.36"
matplotlib = "3.5.1"
pyarrow = "7.0.0"
defopt = "6.3.0"
bravado = "11.0.3"
thefuzz = "0.19.0"
